<?php

namespace App\Services;

class WebsiteAutopilotSchemaService
{
    public function normalizedSchema(): array
    {
        return [
            'identity' => [
                'business_name',
                'founder_name',
                'brand_name',
                'website_title',
                'website_path',
                'custom_domain',
                'website_engine',
                'website_mode',
                'theme_template',
                'theme_label',
            ],
            'market' => [
                'industry',
                'niche',
                'city',
                'state',
                'country',
                'target_audience',
                'primary_icp_name',
                'ideal_customer_profile',
                'pain_points',
                'desired_outcomes',
                'objections',
                'competitor_summary',
                'competitor_price_range',
                'local_market_notes',
                'seo_keyword_cluster',
            ],
            'brand' => [
                'brand_voice',
                'brand_tone',
                'brand_values',
                'visual_direction',
                'primary_color',
                'secondary_color',
                'logo',
                'dark_logo',
                'favicon',
                'og_image',
            ],
            'hero' => [
                'hero_headline',
                'hero_subhead',
                'hero_brief',
                'hero_primary_cta',
                'hero_secondary_cta',
                'hero_image',
                'hero_image_alt',
                'hero_trust_line',
            ],
            'story' => [
                'about_content',
                'story_title',
                'story_subtitle',
                'story_description',
                'story_items',
                'founder_story',
                'credibility_points',
                'philosophy',
            ],
            'conversion' => [
                'core_offer',
                'offer_stack',
                'pricing_strategy',
                'starter_offer',
                'anchor_offer',
                'premium_offer',
                'upsells',
                'cta_goal',
                'booking_goal',
                'lead_magnet',
            ],
            'trust' => [
                'feature_items',
                'why_choose_us_items',
                'testimonials',
                'faq_items',
                'guarantees',
                'proof_points',
                'social_links',
                'google_review_url',
            ],
            'contact' => [
                'contact_email',
                'contact_phone',
                'business_address',
                'business_hours',
                'whatsapp_number',
                'contact_page_copy',
                'contact_image',
            ],
            'seo' => [
                'meta_title',
                'meta_description',
                'indexable_pages',
                'internal_links',
                'blog_keyword_targets',
            ],
            'media' => [
                'media_assets',
                'media_queries',
                'hero_banner',
                'feature_images',
                'testimonial_images',
                'blog_featured_image',
                'faq_image',
                'subscribe_image',
                'fallback_images',
            ],
            'blog' => [
                'blog_title',
                'blog_slug',
                'blog_excerpt',
                'blog_body',
                'blog_featured_image',
                'blog_featured_image_alt',
                'blog_cta',
            ],
            'ops' => [
                'launch_checklist',
                'quality_audit',
                'readiness_flags',
                'publish_status',
            ],
        ];
    }

    public function servioChecklist(): array
    {
        return [
            'website_settings' => [
                'website_title',
                'website_path',
                'custom_domain',
                'theme_template',
                'description',
                'meta_title',
                'meta_description',
                'contact_email',
                'contact_phone',
                'business_address',
                'business_hours',
                'whatsapp_number',
                'google_review_url',
                'about_content',
                'story_title',
                'story_subtitle',
                'story_description',
                'hero_headline',
                'hero_subhead',
                'hero_brief',
                'logo',
                'dark_logo',
                'favicon',
                'primary_color',
                'secondary_color',
                'footer_description',
                'homepage_title',
                'homepage_subtitle',
                'homepage_banner',
                'subscribe_image',
                'faq_image',
                'contact_us_image',
                'store_unavailable_image',
                'no_data_image',
                'order_success_image',
                'auth_image',
                'admin_auth_image',
                'referral_image',
            ],
            'content_modules' => [
                'faq_items',
                'social_links',
                'feature_items',
                'testimonials',
                'why_choose_us_items',
                'story_items',
                'banners',
                'blog_posts',
            ],
            'service_catalog' => [
                'service_categories',
                'services',
                'service_images',
                'service_prices',
                'service_durations',
                'service_capacity',
                'service_availability_days',
                'service_open_time',
                'service_close_time',
                'service_staff_assignments',
                'additional_services',
                'taxes',
                'promocodes',
            ],
            'toggles' => [
                'landing_page',
                'enable_online_booking',
                'enable_service_menu',
                'enable_shop_menu',
                'product_ratting_switch',
                'google_review',
                'payment_process_options',
                'mobile_app_on_off',
                'android_link',
                'ios_link',
            ],
        ];
    }

    public function bazaarChecklist(): array
    {
        return [
            'website_settings' => [
                'website_title',
                'website_path',
                'custom_domain',
                'theme_template',
                'description',
                'meta_title',
                'meta_description',
                'contact_email',
                'contact_phone',
                'business_address',
                'whatsapp_number',
                'about_content',
                'story_title',
                'story_subtitle',
                'story_description',
                'hero_headline',
                'hero_subhead',
                'hero_brief',
                'logo',
                'dark_logo',
                'favicon',
                'primary_color',
                'secondary_color',
                'footer_description',
                'homepage_title',
                'homepage_subtitle',
                'landing_home_banner',
                'subscribe_image',
                'faq_image',
                'maintenance_image',
                'store_unavailable_image',
                'admin_auth_pages_bg_image',
                'order_detail_image',
                'order_success_image',
                'no_data_image',
            ],
            'content_modules' => [
                'faq_items',
                'social_links',
                'feature_items',
                'testimonials',
                'footer_features',
                'blog_posts',
            ],
            'catalog' => [
                'product_categories',
                'products',
                'product_images',
                'variants',
                'extras',
                'sku',
                'prices',
                'original_prices',
                'taxes',
                'stock_management',
                'qty',
                'low_qty',
                'min_order',
                'max_order',
                'shipping_zones',
                'coupons',
            ],
            'toggles' => [
                'landing_page',
                'online_order',
                'delivery_type',
                'product_ratting_switch',
                'google_review',
                'product_section_display',
                'product_display_limit',
                'mobile_app_on_off',
                'android_link',
                'ios_link',
                'tips_settings',
            ],
        ];
    }

    public function servioPayloadMap(): array
    {
        return [
            'website_title' => 'identity.website_title',
            'website_path' => 'identity.website_path',
            'theme_template' => 'identity.theme_template',
            'custom_domain' => 'identity.custom_domain',
            'description' => 'brand.brand_description',
            'meta_title' => 'seo.meta_title',
            'meta_description' => 'seo.meta_description',
            'contact_email' => 'contact.contact_email',
            'contact_phone' => 'contact.contact_phone',
            'business_address' => 'contact.business_address',
            'business_hours' => 'contact.business_hours',
            'whatsapp_number' => 'contact.whatsapp_number',
            'google_review_url' => 'trust.google_review_url',
            'enable_online_booking' => 'toggles.enable_online_booking',
            'enable_service_menu' => 'toggles.enable_service_menu',
            'enable_shop_menu' => 'toggles.enable_shop_menu',
            'about_content' => 'story.about_content',
            'faq_items' => 'trust.faq_items',
            'social_links' => 'trust.social_links',
            'feature_items' => 'trust.feature_items',
            'testimonials' => 'trust.testimonials',
            'story_items' => 'story.story_items',
            'story_title' => 'story.story_title',
            'story_subtitle' => 'story.story_subtitle',
            'story_description' => 'story.story_description',
            'hero_headline' => 'hero.hero_headline',
            'hero_subhead' => 'hero.hero_subhead',
            'hero_brief' => 'hero.hero_brief',
            'media_assets' => 'media.media_assets',
            'media_queries' => 'media.media_queries',
        ];
    }

    public function bazaarPayloadMap(): array
    {
        return [
            'website_title' => 'identity.website_title',
            'website_path' => 'identity.website_path',
            'theme_template' => 'identity.theme_template',
            'custom_domain' => 'identity.custom_domain',
            'description' => 'brand.brand_description',
            'meta_title' => 'seo.meta_title',
            'meta_description' => 'seo.meta_description',
            'contact_email' => 'contact.contact_email',
            'contact_phone' => 'contact.contact_phone',
            'business_address' => 'contact.business_address',
            'whatsapp_number' => 'contact.whatsapp_number',
            'about_content' => 'story.about_content',
            'faq_items' => 'trust.faq_items',
            'social_links' => 'trust.social_links',
            'feature_items' => 'trust.feature_items',
            'testimonials' => 'trust.testimonials',
            'story_items' => 'story.story_items',
            'story_title' => 'story.story_title',
            'story_subtitle' => 'story.story_subtitle',
            'story_description' => 'story.story_description',
            'hero_headline' => 'hero.hero_headline',
            'hero_subhead' => 'hero.hero_subhead',
            'hero_brief' => 'hero.hero_brief',
            'media_assets' => 'media.media_assets',
            'media_queries' => 'media.media_queries',
        ];
    }
}
